language: python
sudo: false
python:
  - "2.7"
  - "3.4"
#  - "3.5" # not supported by travis yet
install:
#  - "pip install ."
script: make test
notifications:
  email: false
#  irc:
#    channels:
#      - "irc.freenode.org#tmda"
#    on_success: change
#    on_failure: always
#    template:
#      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
#    skip_join: true

