#!/bin/bash
if ! `grep -q MHIDIR ~/.mhirc`; then
    echo "Put a line like 'MHIDIR=/path/to/dir/with/mhi.py' in your ~/.mhirc"
    exit 1
fi

export `grep MHIDIR ~/.mhirc | sed 's/ //g'`
MHI=$MHIDIR/mhi.py

if [ ! -f $MHI ]; then
    echo "There's no mhi.py in your MHIDIR ($MHIDIR) as specified in your ~/.mhirc"
    exit 1
fi
$MHI `basename $0` "$@"
